kind: pipeline
type: docker
name: default

steps:
- name: frontend
  image: node
  commands:
  - cd frontend
  - npm install
  - npm run build

- name: serve
  image: nginx
  commands:
  - cp -R frontend/dist /usr/share/nginx/html
  - nginx -g 'daemon off;'

