kind: pipeline
type: docker

name: my-app

steps:
  - name: build-and-deploy
    image: docker:20
    commands:
      - docker build -t my-app .
      - docker run -d -p 8080:80 --name my-app my-app

