

# steps:
# - name: frontend
#   image: node:18-alpine
#   commands:
#   - cd frontend
#   - npm install
#   - npm run build

# - name: serve
#   image: nginx:stable-perl
#   commands:
#   - rm -rf /usr/share/nginx/html
#   - cp -R frontend/dist /usr/share/nginx/html
#   - nginx -g "daemon off;"

kind: pipeline
name: default
type: docker

steps:
- name: test
  image: prakash2403/ubuntu-docker-cli:intel
  volumes:
  - name: dockersock
    path: /var/run/
  commands:
  - sleep 500 # give docker enough time to start
  - docker build . -t my-app
  - docker run -d -p 8080:80 my-app
  - docker ps -a 

services:
- name: docker
  image: prakash2403/ubuntu-docker-cli:intel
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run/

volumes:
- name: dockersock
  host:
    path: /var/run/
